global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: "alloy"
    metrics_path: /metrics
    static_configs:
      - targets: ["alloy:12345"]

  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "tempo"
    metrics_path: /metrics
    static_configs:
      - targets: ["tempo:3200"]